name: Anguished (Condition)
automation:
  - type: target
    target: each
    effects:
      - type: ieffect2
        name: Anguished
        desc: "An anguished character is miserable, and has disadvantage on all ability checks, attack rolls, and saving throws. There is only one way to recover from such depths of desperation—the Player-hero must experience a bout of madness."
        effects:
          attack_advantage: -1  # Disadvantage on attacks
          save_dis: ["all"]    # Disadvantage on all saves
          check_dis: ["all"]   # Disadvantage on all ability checks
        buttons:
          - label: Remove Anguish
            verb: "recovers from their anguish through madness"
            style: "3"
            automation:
              - type: remove_ieffect
              - type: text
                text: "Only through experiencing madness can a character recover from anguish."
_v: 2
